### PR TITLE
Fixed PDF generation functions

### PR DESCRIPTION
**Pull request by mariodlrosario**
Training, data augmentation, QC and prediction tested and working

### CODE REVIEW

**Comment by IvanHCenalmor** [comment]
Hello @mariodlrosario ,

I have looked at the changes that you propose, and there were other notebooks with the same problems. I have updated them in commit [2a77ebe](https://github.com/HenriquesLab/ZeroCostDL4Mic/commit/2a77ebe8db4d58d1e4c968eb64b23cfb39921b37), here is included the pix2pix model you changed. Apart from the error you solved, there were other details that needed to be fixed:

1. 
```
- df = pd.read_csv(path, delimiter = "\n")
+ df = pd.read_csv(path)
```

2.
```
-  file.writelines(item + '\\n')
+  file.writelines(item)
```

3.
```
-  <font size="7" face="Courier New" >
+  <font size="7" face="Courier" >
```

4. Finally, after `pdf.multi_cell(...)`, `pdf.ln(1)`has been added.

Thank you for the feedback, I hope that now you can use the pix2pix notebook without problems :)

**Comment by esgomezm** [comment]
Hi @IvanHCenalmor 

There's a conflict in this pull request so the PR cannot be merged. Did you apply Marios's changes? If yes, then this PR has to be closed without merging it. If no, Mario please, (1) close this PR, (2) take the last version of this repo with the new pix2pix notebook modified by Iván, (3) integrate your changes and (4) make a commit.

Thank you!

**Comment by IvanHCenalmor** [comment]
Hi @esgomezm ,

I applied the changes that @mariodlrosario proposed, but as there where more changes that needed to be made I solved it in another commit. So yes, this PR should be closed without merging as it has already been solved in commit [2a77ebe](https://github.com/HenriquesLab/ZeroCostDL4Mic/commit/2a77ebe8db4d58d1e4c968eb64b23cfb39921b37).

**Comment by IvanHCenalmor** [comment]
I hope that with the changes that have been made everything works, if not please be free to open another PR.

**Pull request closed without merging**
