### PR TITLE
Faster prediction, more plots and fixed errors

### PR DESCRIPTION
**Pull request by IvanHCenalmor**

### CODE REVIEW

**Comment by esgomezm** [comment]
Hey @IvanHCenalmor 

shall we wait a bit to merge this pr?

**Comment by IvanHCenalmor** [comment]
Yes, of course, now with all the changes that have been made in these 9 moths the notebooks I think that they are a bit obsolete.

**Comment by esgomezm** [comment]
Ok, then I will close this PR and once it's ready you make it again?

**Comment by IvanHCenalmor** [comment]
Perfect!

**Pull request closed without merging**
