### PR TITLE
Integrate bioimageio.core library into the 3D U-Net notebook

### PR DESCRIPTION
**Pull request by esgomezm**
The notebook is almost ready. 

Missing points:
- Include the information about the `training_data`. This needs to be done in the 2D U-Net notebook as well.
 
Concerns:
- I noticed that some of the parameters of the `build_model` function have changed. (For example `input_name`  now is `input_names` and the same for the output). Is there anything else? It's just to update the 2D U-Net notebook with these changes.
- Should we freeze the version of the bioimageio.core that's being installed in the notebook? It would be a bit annoying to maintain the notebooks and keep them updated but at the same time, if there's an issue with users, it makes it easier to know where the problem could be.

@constantinpape @FynnBe

### CODE REVIEW

**Comment by constantinpape** [comment]
Hi @esgomezm,

> * Include the information about the `training_data`. This needs to be done in the 2D U-Net notebook as well.

Yes, I will include this in the next bioimageio.core release (0.5.0), should be there tomorrow or early next week.

> * I noticed that some of the parameters of the `build_model` function have changed. (For example `input_name`  now is `input_names` and the same for the output). Is there anything else? It's just to update the 2D U-Net notebook with these changes.

Yes, I changed these because the singular did not make sense.
There are two more changes introduced in https://github.com/bioimage-io/core-bioimage-io-python/pull/229, that will also be part of 0.5.0 that concern `cite` and `preprocessing` / `postprocessing`. This will be it for 0.5.0 and we will not include any more breaking changes in any 0.5.X release.

> * Should we freeze the version of the bioimageio.core that's being installed in the notebook? It would be a bit annoying to maintain the notebooks and keep them updated but at the same time, if there's an issue with users, it makes it easier to know where the problem could be.

Yes, it makes sense to still adapt to the 0.5 changes (to also support `training_data`), and then freeze the version to be <0.6.

**Comment by esgomezm** [comment]
Thank you @constantinpape 

> Yes, I will include this in the next bioimageio.core release (0.5.0), should be there tomorrow or early next week.

Ok, please, let me know when it is ready. Also, if possible, could you point me to the function that creates the fields or the description of the field so I can properly use it in the notebook?

> Yes, it makes sense to still adapt to the 0.5 changes (to also support training_data), and then freeze the version to be <0.6.

Ok, once 0..5.X is ready, I will force the notebooks to install the latest 0.5 version.

**Comment by constantinpape** [comment]
Hi @esgomezm,
bioimageio.core 0.5.0 is released now and available on pypi: https://pypi.org/project/bioimageio.core.
There are three changes to `build_model`:
- `cite` is now passed as `[{"text": "My publication", "doi": "doi/xyz123"}]` instead of `{"My publication": "doi/xyz123"}`.
- `preprocessing` is called as [[{"name": "binarzie", "kwargs": {"threshold": 0.5}}]] instead of `[{"binarize": {"threshold": 0.5}}]`
- `parent` is called as `{"uri": "model_id", "sha256": "..."}` instead of `("model_id", "...")`

These were all the changes necessary to have the function signature compatible with the spec. You can find the full function signature [here](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/build_spec/build_model.py#L592-L722). And the example notebook is [here](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/example/bioimageio-core-usage.ipynb).
Let me know if you run into any issues updating this.

**Comment by esgomezm** [comment]
Hi @constantinpape 

Thank you for the updates!! I'm trying it now. Is the training_data field also included?

**Comment by constantinpape** [comment]
> Thank you for the updates!! I'm trying it now. Is the training_data field also included?

Yes: https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/build_spec/build_model.py#L639

You can simply pass `trainining_data={"id": "..."}` for a dataset on bioimage.io or `training_data={"source": "..."}` if the training data is available via url or as a local file. (In the second case you can also pass additional fields, e.g. `description`)

**Comment by constantinpape** [comment]
> OK! Do you know if the arabidopsis data is published in the BMZ? I don't find it, sorry

Yeah, it's not published yet; I can add it later and ping you.

**Comment by esgomezm** [comment]
> Yeah, it's not published yet; I can add it later and ping you.

Don't worry, I'll try just with different links, it's to check that it works

**Comment by constantinpape** [comment]
Here's the PR to add the plant datasets: https://github.com/ilastik/bioimage-io-resources/pull/49.

**Comment by esgomezm** [comment]
Ok! Seems to work. Here is the exported model: https://drive.google.com/file/d/10NkuL2TPGdUWz2GqVLWnSo-md0MXh8w6/view?usp=sharing

Could you try it in ilastik please?

**Comment by constantinpape** [comment]
Sure, gonna try it in a sec.

**Comment by constantinpape** [comment]
Can you please grant me access, @esgomezm:
image

**Comment by esgomezm** [comment]
it should work now

**Comment by constantinpape** [comment]
Thanks @esgomezm. I have downloaded it now and there are a few issues in ilastik, but they are unrelated to the model itself as far as I can see. It works fine with `bioimageio test-model`, so the issue is on the ilastik side.
I will bring this up with the ilastik team; please go ahead and merge this once you think it's ready.

**Comment by constantinpape** [comment]
xref https://github.com/ilastik/ilastik/issues/2555

**Pull request merged**
