### PR TITLE
BioImage Model Zoo model export

### PR DESCRIPTION
**Pull request by esgomezm**

### CODE REVIEW

**Comment by uschmidt83** [comment]
> I'm preparing the export for StarDist2D notebook but I wonder whether it's possible to add extra information to the yaml file using the StarDist library.

Yes, you can use the parameter [`overwrite_spec_kwargs`](https://github.com/stardist/stardist/blob/1cb0bd597e4b7ca7ca2dfadd3f266be925d7e2da/stardist/bioimageio_utils.py#L373-L374) to do that.

> When I load a BMZ model using `import_bioimageio`, is there any way in which I could get the name of the Keras model? (wouldn't it be risky assuming that it's always `stardist_weights.h5`?)

By name of the Keras model, you mean name of weights file? The name of this file is part of the yaml (see [code that retrieves the weights file](https://github.com/stardist/stardist/blob/1cb0bd597e4b7ca7ca2dfadd3f266be925d7e2da/stardist/bioimageio_utils.py#L440-L447)).

> In the notebook, the user specifies some parameters regarding the model architecture, so if I load directly the pre-trained model with `import_bioimageio` instead of loading only the weights, I would risk changing the architecture specified by the user.

The entire StarDist config is saved to the yaml file during model export, hence [`import_bioimageio`](https://github.com/stardist/stardist/blob/1cb0bd597e4b7ca7ca2dfadd3f266be925d7e2da/stardist/bioimageio_utils.py#L409) will create a model with the correct architecture before loading the weights.

**Comment by esgomezm** [comment]
Hi @uschmidt83 

thank you for the quick answer! 

> Yes, you can use the parameter [overwrite_spec_kwargs](https://github.com/stardist/stardist/blob/1cb0bd597e4b7ca7ca2dfadd3f266be925d7e2da/stardist/bioimageio_utils.py#L373-L374) to do that.

Ok, would it be something like `overwrite_spec_kwargs = {'description': 'T-cell segmentation', 'datasets': {'id': 'XXXX'} }`?
I can try it and come back.

> By name of the Keras model, you mean name of weights file? The name of this file is part of the yaml (see [code that retrieves the weights file](https://github.com/stardist/stardist/blob/1cb0bd597e4b7ca7ca2dfadd3f266be925d7e2da/stardist/bioimageio_utils.py#L440-L447)).
> The entire StarDist config is saved to the yaml file during model export, hence [import_bioimageio](https://github.com/stardist/stardist/blob/1cb0bd597e4b7ca7ca2dfadd3f266be925d7e2da/stardist/bioimageio_utils.py#L409) will create a model with the correct architecture before loading the weights.

Yes, I know. Here the situation is a bit different and we actually have the same concern for the rest of the notebooks: we want to give the user the chance to set up the architecture and training, but also load a pre-trained model. From the BMZ specifications, it's not clear what's the configuration of the architecture unless the developer writes it down or adds the pdf exported in ZCDL4M, for example. There will be a smoother solution in the future but the easiest one now is to try to load the weights from a specific model checkpoint (that's why I asked about the naming). Also, I can add a friendlier error message saying "The architecture of the pre-trained model doesn't match the defined parameters. Please check it". Or something even more specific and descriptive.

**Comment by uschmidt83** [comment]
> Ok, would it be something like `overwrite_spec_kwargs = {'description': 'T-cell segmentation', 'datasets': {'id': 'XXXX'} }`? I can try it and come back.

Yes.

Thinking about it, I only see problems with this approach if you want to update a nested dictionary. For example, I don't think it's possible to add an author to the existing `authors` dictionary, you can only overwrite it entirely. Maybe we should add the possibility (and then remove `overwrite_spec_kwargs`?) to pass a function that takes the spec dictionary as input and returns a modified copy of it? Thoughts on this, @constantinpape?

> we want to give the user the chance to set up the architecture and training, but also load a pre-trained model.

I don't understand at all. What's the use case?

**Comment by constantinpape** [comment]
> Thinking about it, I only see problems with this approach if you want to update a nested dictionary. For example, I don't think it's possible to add an author to the existing `authors` dictionary, you can only overwrite it entirely

Yes, I think that's true.

> Maybe we should add the possibility (and then remove `overwrite_spec_kwargs`?) to pass a function that takes the spec dictionary as input and returns a modified copy of it?

I like that idea! It would be more flexible than the current `overwrite_spec_kwargs` solution since the user could choose to over-write or extend the defaults. Probably makes most sense to discuss this further in an issue or PR in the stardist repo.

> Here the situation is a bit different and we actually have the same concern for the rest of the notebooks: we want to give the user the chance to set up the architecture and training, but also load a pre-trained model. From the BMZ specifications, it's not clear what's the configuration of the architecture unless the developer writes it down or adds the pdf exported in ZCDL4M,

I don't really see the issue in the case for the zero-cost stardist notebook. Afaict you only expose pretty limited relevant model configurations (e.g. number of rays and scaling factor) in the notebook:
https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/BioImage.io%20notebooks/StarDist_2D_ZeroCostDL4Mic_BioImageModelZoo_export.ipynb#scrollTo=ewpNJ_I0Mv47

As @uschmidt83 said, all of this is stored in the rdf.yaml in `config:stardist:config`, see https://github.com/stardist/stardist/blob/master/stardist/bioimageio_utils.py#L267. So you can just read the values from there and see if they are consistent with the user choices.

**Comment by constantinpape** [comment]
@uschmidt83 we discussed the point raised by @esgomezm today in the bioimageio meeting and the issue here is that after deserializing the model with `import_bioimageio` the information contained in the rdf.yaml cannot be easily accessed since it's not contained in the model. There is a work-around of using `bioimageio.core` functionality again to load this information, but we think that it would be cleaner to add this information to the loaded model in the first place.

I made a PR with a proposal to achieve this: https://github.com/stardist/stardist/pull/187. Let us know what you think.

**Comment by constantinpape** [comment]
Hey @esgomezm,
with the changes from https://github.com/stardist/stardist/pull/187 you can now get the bioimageio rdf for the stardist model via
```py
bio_model = bioimageio.core.load_resource_description(f"{model_folder}/bioimageio/rdf.yaml")
```
You will need stardist 0.8.1 for this.

**Comment by esgomezm** [comment]
Hey @constantinpape 

I'm trying the new version of StarDist. Now, the entire BMZ model is downloaded in a different folder. Is this the expected behavior or do you wanted just to download the yaml file?

Screenshot 2022-03-25 at 11 43 32

**Comment by uschmidt83** [comment]
> I'm trying the new version of StarDist. Now, the entire BMZ model is downloaded in a different folder. Is this the expected behaviour or do you want just to download the YAML file?

This is the intended behavior.

> Also, for some reason this yaml file does only contain the information about the TF weights.

What do you mean? We never had any other weights listed there.

> Then, the name of the keras weights is different (`weights_bioimageio.h5` and `stardist_weights.h5`).

This is done on purpose, such that the imported bioimage.io weights in the main StarDist folder are always called `weights_bioimageio.h5`, regardless of the name in the `rdf.yaml`.

**Comment by constantinpape** [comment]
> Now, the entire BMZ model is downloaded in a different folder. Is this the expected behaviour or do you want just to download the YAML file?

That's the expected behavior. All files need to be downloaded so that this model is valid for `bioimageio.core`. (It will not work properly if we only download the yaml without the files listed in it).

> Also, for some reason this yaml file does only contain the information about the TF weights.

Yes, that's also expected: we can't register both weights for the model, since they produce outputs of different size, something not currently supported by our spec.

> Then, the name of the keras weights is different (`weights_bioimageio.h5` and `stardist_weights.h5`). I think this one needs to be changed as in the stardist config, the information is different:

That may be a bit confusing, but it's the intended behavior and shouldn't cause any issues if you know about it.

(@uschmidt83 posted just as I was writing this, but I think we give the same answers ;))

**Comment by uschmidt83** [comment]
> > Then, the name of the keras weights is different (`weights_bioimageio.h5` and `stardist_weights.h5`). I think this one needs to be changed as in the stardist config, the information is different:
> 
> That may be a bit confusing, but it's the intended behavior and shouldn't cause any issues if you know about it.

Regarding `weights_bioimageio.h5`, you can easily find out to which file in the "bioimageio" sub-folder these weights correspond to via the `rdf.yaml`.

```yaml
stardist:
    weights: stardist_weights.h5
```

**Comment by esgomezm** [comment]
OK, thank you @uschmidt83 and @constantinpape! everything is clear now

**Comment by esgomezm** [comment]
The StarDist model is ready. As said in the meeting, I will wait for the other UNet notebooks (the semantic one included) to be ready to merge the pull request.

**Comment by constantinpape** [comment]
Hey @esgomezm, do you think this can be merged, so that the bioimage.io functionality for stardist is available in the main notebooks?

**Comment by esgomezm** [comment]
Hi @constantinpape! I need to correct the 2DUNet to make sense with the last version of the bioimgeio.core library. The rest are ok

**Comment by constantinpape** [comment]
> Hi @constantinpape! I need to correct the 2DUNet to make sense with the last version of the bioimgeio.core library. The rest are ok

Ok, do you think you could do that soon? Would be great to have it in for all the use-cases!

**Pull request merged**
